### ISSUE TITLE
htm-teidivedition: span elements get the same id

### ISSUE THREAD

**Issue by enury** [EpiDoc/Stylesheets#3]
There is a slight problem with this line of code: 
https://github.com/EpiDoc/Stylesheets/blob/fd8c169c63d986e92b7321dddaca1e62f7495700/htm-teidivedition.xsl#L64

For instance in papyrus TM905 (http://papyri.info/ddbdp/p.cair.zen;2;59261), where there are two divs with @n="ctr", it means that the spans with class "textpartnumber" will both get the same id "abctr". The CSS/jquery selectors were not very happy about it!

**Comment by sarcanon** [comment]
I agree the code should try a little harder to ensure it does not generate a non-unique @id value. The code implicitly assumes values of @n are unique among textpart divs.

I will create a ticket in the EpiDoc issue tracker for this item, however it will not make it into v 9.1 release. As an interim workaround, perhaps you may want to consider forking your local version of this stylesheet, and modifying line 64 to be something like:

`<span class="textpartnumber" id="{$div-type}ab{$div-loc}{@n}{position()}">`

This should ensure uniqueness of the <span> element's @id value and thus not subvert your selectors.

**Comment by enury** [comment]
Thanks! Actually my temporary fix was to add **@n** to the class, so that I could select both center parts of the text:

`<span class="textpartnumber {@n}" id="{$div-type}ab{$div-loc}{@n}">`

**Comment by paregorios** [comment]
Fix for this will now be tracked on the EpiDoc Bug Report tracker at Sourceforge: https://sourceforge.net/p/epidoc/bugs/176/
